routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home_full', 'HomeController@index_full')->name('home_full');


Route::group(['namespace' => 'Admin',  'middleware' => ['auth', 'can:isAdmin'], 'prefix' => 'admin'], function (){

    /**
     *      Admin routes
     */
    Route::get('/accident/export', 'AccidentController@export')->name('accident_export');
    Route::get('/lessons/export', 'LessonsController@export')->name('lesson_export');

    Route::resource('user', 'UserController');
    Route::resource('accident', 'AccidentController');
    Route::resource('seasons', 'SeasonsController');
    Route::resource('lessons', 'LessonsController');
    Route::resource('niveau', 'NiveauController');
    Route::resource('accident-place', 'AccidentPlaceController');
    Route::resource('weather', 'WeatherController');
    Route::resource('snow-condition', 'SnowConditionController');
    Route::resource('accident-type', 'AccidentTypeController');
    Route::resource('piste-rescue', 'PisteRescueController');
    Route::resource('accident-gravity', 'AccidentGravityController');
    Route::resource('protection', 'ProtectionController');
    Route::resource('injury-type', 'InjuryTypeController');
    Route::resource('body-part', 'BodyPartController');
    Route::resource('discipline', 'DisciplineController');
    Route::resource('age-category', 'AgeCategoryController');
    Route::resource('accident-activity', 'AccidentActivityController');

});

Route::group(['namespace' => 'User',  'middleware' => ['auth', 'can:isSchool'], 'prefix' => 'user'], function (){

    /**
     *      User (=school) routes
     */

    Route::get('/lessons/{id}/export', 'LessonsController@export')->name('export_lesson');
    Route::get('/accident/{id}/export', 'AccidentController@export')->name('export_accident');

    Route::resource('lessons', 'LessonsController');
    Route::resource('accident', 'AccidentController');
    Route::get('/import', 'ImportLessonController@index')->name('import');
    Route::post('/import/upload', 'ImportLessonController@upload')->name('import_upload');
});

/**
 *      change locale
 */
Route::get('lang/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        session(['locale' => $locale]);
    }
    return redirect()->back();
})->name('language');

app/Accident.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Accident extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'accidents';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    //protected $dates = ['date'];

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'date', 'accident_place_id', 'accident_activity_id', 'teacher', 'weather_id', 'snow_conditions_id', 'accident_type_id', 'witnesses', 'piste_rescue_id', 'description', 'accident_gravity_id', 'protection_id', 'injured_person', 'age_category_id', 'sex', 'discipline_id', 'niveau_id', 'injured_lastname', 'injured_firstname', 'injured_birthdate', 'injured_street', 'injured_plz', 'injured_town', 'injured_country', 'injured_holiday_street', 'injured_holiday_plz', 'injured_holiday_town', 'user_id'];

    public function getDateHumanAttribute($date)
    {
        return Carbon::parse($date)->format('d.m.Y');
    }

    public function accident_place()
    {
        return $this->belongsTo('App\AccidentPlace');
    }
    public function accident_activity()
    {
        return $this->belongsTo('App\AccidentActivity');
    }
    public function weather()
    {
        return $this->belongsTo('App\Weather');
    }
    public function snow_condition()
    {
        return $this->belongsTo('App\SnowCondition', 'snow_conditions_id');
    }
    public function accident_type()
    {
        return $this->belongsTo('App\AccidentType');
    }
    public function piste_rescue()
    {
        return $this->belongsTo('App\PisteRescue');
    }
    public function accident_gravity()
    {
        return $this->belongsTo('App\AccidentGravity');
    }
    public function protection()
    {
        return $this->belongsTo('App\Protection');
    }
    public function body_parts()
    {
        return $this->belongsToMany('App\BodyPart');
    }
    public function injury_types()
    {
        return $this->belongsToMany('App\InjuryType');
    }
    public function getBodyPartsListAttribute()
    {
        return implode(', ', $this->body_parts()->pluck('name_' . App::getLocale())->toArray());
    }
    public function getInjuryTypeListAttribute()
    {
        return implode(', ', $this->injury_types()->pluck('name_' . App::getLocale())->toArray());
    }
    public function getInjuredPersonStrAttribute()
    {
        return $this->injured_person === 'guest' ? __('entities.guest') : __('entities.teacher');
    }
    public function age_category()
    {
        return $this->belongsTo('App\AgeCategory');
    }
    public function discipline()
    {
        return $this->belongsTo('App\Discipline');
    }
    public function niveau()
    {
        return $this->belongsTo('App\Niveau');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/Admin/AccidentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\AccidentActivity;
use App\AccidentGravity;
use App\AccidentPlace;
use App\AccidentType;
use App\AgeCategory;
use App\BodyPart;
use App\Discipline;
use App\Exports\AccidentsExport;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Accident;
use App\InjuryType;
use App\Niveau;
use App\PisteRescue;
use App\Protection;
use App\SnowCondition;
use App\Weather;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class AccidentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $accident = Accident::where('user_id', Auth::user()->id)
                ->where('title', 'LIKE', "%$keyword%")
                        ->orWhere('date', 'LIKE', "%$keyword%")
                        ->orWhere('accident_place_id', 'LIKE', "%$keyword%")
                        ->orWhere('accident_activity_id', 'LIKE', "%$keyword%")
                        ->orWhere('teacher', 'LIKE', "%$keyword%")
                        ->orWhere('weather_id', 'LIKE', "%$keyword%")
                        ->orWhere('snow_conditions_id', 'LIKE', "%$keyword%")
                        ->orWhere('accident_type_id', 'LIKE', "%$keyword%")
                        ->orWhere('witnesses', 'LIKE', "%$keyword%")
                        ->orWhere('piste_rescue_id', 'LIKE', "%$keyword%")
                        ->orWhere('description', 'LIKE', "%$keyword%")
                        ->orWhere('accident_gravity_id', 'LIKE', "%$keyword%")
                        ->orWhere('protection_id', 'LIKE', "%$keyword%")
                        ->orWhere('injured_person', 'LIKE', "%$keyword%")
                        ->orWhere('age_category_id', 'LIKE', "%$keyword%")
                        ->orWhere('sex', 'LIKE', "%$keyword%")
                        ->orWhere('discipline_id', 'LIKE', "%$keyword%")
                        ->orWhere('niveau_id', 'LIKE', "%$keyword%")
                        ->orWhere('injured_lastname', 'LIKE', "%$keyword%")
                        ->orWhere('injured_firstname', 'LIKE', "%$keyword%")
                        ->orWhere('injured_birthdate', 'LIKE', "%$keyword%")
                        ->orWhere('injured_street', 'LIKE', "%$keyword%")
                        ->orWhere('injured_plz', 'LIKE', "%$keyword%")
                        ->orWhere('injured_town', 'LIKE', "%$keyword%")
                        ->orWhere('injured_country', 'LIKE', "%$keyword%")
                        ->orWhere('injured_holiday_street', 'LIKE', "%$keyword%")
                        ->orWhere('injured_holiday_plz', 'LIKE', "%$keyword%")
                        ->orWhere('injured_holiday_town', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $accident = Accident::latest()->paginate($perPage);
        }

        return view('admin.accident.index', compact('accident'));
    }

    /**
     * @return array
     */
    public static function getForeignKeys(){
        return [
            'accident_places' => AccidentPlace::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'accident_activities' => AccidentActivity::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'weather' => Weather::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'snow_conditions' => SnowCondition::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'accident_types' => AccidentType::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'piste_rescues' => PisteRescue::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'accident_gravities' => AccidentGravity::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'protections' => Protection::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'age_categories' => AgeCategory::orderBy('id', 'desc')->pluck('name','id'),
            'disciplines' => Discipline::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'niveaux' => Niveau::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'body_parts' => BodyPart::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id'),
            'injury_types' => InjuryType::orderBy('id', 'desc')->pluck('name_' . App::getLocale(),'id')
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $foreign_keys = self::getForeignKeys();
        return view('admin.accident.create')->with('fks', $foreign_keys);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {

        $this->validate($request, [
			'title' => 'required',
			'date' => 'required',
			'accident_place_id' => 'required',
			'accident_activity_id' => 'required',
			'accident_gravity_id' => 'required',
			'protection_id' => 'required',
			'injured_person' => 'required',
			'age_category_id' => 'required',
			'sex' => 'required',
			'discipline_id' => 'required',
			'niveau_id' => 'required'
		]);
        $requestData = $request->all();

        $accident = Accident::create($requestData);

        // many to many
        $accident->body_parts()->sync($request->post('body_part_ids', []));
        $accident->injury_types()->sync($request->post('injury_type_ids', []));

        return redirect('user/accident')->with('flash_message', 'Accident added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $accident = Accident::findOrFail($id);

        return view('admin.accident.show', compact('accident'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $foreign_keys = self::getForeignKeys();
        $accident = Accident::findOrFail($id);

        return view('admin.accident.edit', compact('accident'))->with('fks', $foreign_keys);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
			'title' => 'required',
			'date' => 'required',
			'accident_place_id' => 'required',
			'accident_activity_id' => 'required',
			'accident_gravity_id' => 'required',
			'protection_id' => 'required',
			'injured_person' => 'required',
			'age_category_id' => 'required',
			'sex' => 'required',
			'discipline_id' => 'required',
			'niveau_id' => 'required'
		]);
        $requestData = $request->all();

        $accident = Accident::findOrFail($id);
        $accident->update($requestData);

        // many to many
        $accident->body_parts()->sync($request->post('body_part_ids', []));
        $accident->injury_types()->sync($request->post('injury_type_ids', []));

        return redirect('user/accident')->with('flash_message', 'Accident updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Accident::destroy($id);

        return redirect('user/accident')->with('flash_message', 'Accident deleted!');
    }

    public function export(Request $request)
    {

        $file_name = Carbon::now()->toDateString() . '_accidents.xlsx';
        return Excel::download(new AccidentsExport(), $file_name);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $user = User::where('name', 'LIKE', "%$keyword%")
                ->orWhere('password', 'LIKE', "%$keyword%")
                ->orWhere('company', 'LIKE', "%$keyword%")
                ->orWhere('plz', 'LIKE', "%$keyword%")
                ->orWhere('town', 'LIKE', "%$keyword%")
                ->orWhere('language_id', 'LIKE', "%$keyword%")
                ->orWhere('region_id', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $user = User::latest()->paginate($perPage);
        }

        return view('admin.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'name' => 'required',
            'id' => 'required|unique:users',
            'email' => 'required|unique:users',
            'password' => 'required'
		]);
        $requestData = $request->all();
        $requestData['password'] = bcrypt($requestData['password']);

        User::create($requestData);

        return redirect('admin/user')->with('flash_message', 'User added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users'
		]);
        $requestData = $request->all();

        if($requestData['password'] == null){
            unset($requestData['password']);
        }else{
            $requestData['password'] = bcrypt($requestData['password']);
        }

        $user = User::findOrFail($id);
        $user->update($requestData);

        return redirect('admin/user')->with('flash_message', 'User updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        User::destroy($id);

        return redirect('admin/user')->with('flash_message', 'User deleted!');
    }
}

resources/views/user/accident/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.create_new_accident') }}</div>
                    <div class="card-body">
                        <a href="{{ url('/user/accident') }}" title="{{ __('entities.back') }}"><button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('entities.back') }}</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ url('/user/accident') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('user.accident.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/accident/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.edit') }} «{{ $accident->title }}»</div>
                    <div class="card-body">
                        <a href="{{ url('/user/accident') }}" title="{{ __('entities.back') }}"><button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('entities.back') }}</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ url('/user/accident/' . $accident->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('user.accident.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/accident/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.accident') }} «{{ $accident->title }}»</div>
                    <div class="card-body">

                        <a href="{{ url('/user/accident') }}" title="{{__('entities.back') }}">
                            <button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left"
                                                                              aria-hidden="true"></i> {{__('entities.back') }}
                            </button>
                        </a>
                        <a href="{{ url('/user/accident/' . $accident->id . '/edit') }}"
                           title="{{__('entities.edit') }} Accident">
                            <button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o"
                                                                      aria-hidden="true"></i> {{__('entities.edit') }}
                            </button>
                        </a>

                        <form method="POST" action="{{ url('user/accident' . '/' . $accident->id) }}"
                              accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-outline-primary btn-sm" title="Delete Accident"
                                    onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o"
                                                                                             aria-hidden="true"></i> {{__('entities.delete') }}
                            </button>
                        </form>

                        <a href="{{ url('/user/accident/' . $accident->id . '/export') }}"
                           title="{{__('entities.export') }}">
                            <button class="btn btn-outline-primary btn-sm"><i
                                    class="fa fa-file-excel-o"
                                    aria-hidden="true"></i> {{__('entities.export') }}</button>
                        </a>

                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table table-sm ">
                                <tbody>
                                <tr>
                                    <th> {{ __('entities.accident_title') }}</th>
                                    <td> {{ $accident->title }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_date') }}</th>
                                    <td> {{ \Carbon\Carbon::parse($accident->date)->format('d.m.Y') }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_place') }}</th>
                                    <td> {{ $accident->accident_place['name_' . Config::get('app.locale') ]}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_activity') }}</th>
                                    <td> {{ $accident->accident_activity['name_' . Config::get('app.locale') ]}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_teacher') }}</th>
                                    <td> {{ $accident->teacher }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_weather') }}</th>
                                    <td> {{ $accident->weather['name_' . Config::get('app.locale') ]}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_snow_conditions') }}</th>
                                    <td> {{ $accident->snow_condition['name_' . Config::get('app.locale') ]}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_type') }}</th>
                                    <td> {{ $accident->accident_type['name_' . Config::get('app.locale') ]}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_witnesses') }}</th>
                                    <td> {{ $accident->witnesses }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_piste_rescue') }}</th>
                                    <td> {{ $accident->piste_rescue['name_' . Config::get('app.locale') ] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_description') }}</th>
                                    <td> {{ $accident->description }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_gravity') }}</th>
                                    <td> {{ $accident->accident_gravity['name_' . Config::get('app.locale') ] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_protection') }}</th>
                                    <td> {{ $accident->protection['name_' . Config::get('app.locale') ] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_body_part') }}</th>
                                    <td> {{ $accident->body_parts_list}} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injury_type') }}</th>
                                    <td> {{ $accident->injury_type_list }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_person') }}</th>
                                    <td> {{ $accident->injured_person_str }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_age_category') }}</th>
                                    <td> {{ $accident->age_category['name'] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_sex') }}</th>
                                    <td> {{ $accident->sex }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_discipline') }}</th>
                                    <td> {{ $accident->discipline['name_' . Config::get('app.locale') ] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_niveau') }}</th>
                                    <td> {{ $accident->niveau['name_' . Config::get('app.locale') ] }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_lastname') }}</th>
                                    <td> {{ $accident->injured_lastname }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_firstname') }}</th>
                                    <td> {{ $accident->injured_firstname }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_birthdate') }}</th>
                                    <td> {{ $accident->injured_birthdate }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_street') }}</th>
                                    <td> {{ $accident->injured_street }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_plz') }}</th>
                                    <td> {{ $accident->injured_plz }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_town') }}</th>
                                    <td> {{ $accident->injured_town }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_country') }}</th>
                                    <td> {{ $accident->injured_country }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_holiday_street') }}</th>
                                    <td> {{ $accident->injured_holiday_street }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_holiday_plz') }}</th>
                                    <td> {{ $accident->injured_holiday_plz }} </td>
                                </tr>
                                <tr>
                                    <th> {{ __('entities.accident_injured_holiday_town') }}</th>
                                    <td> {{ $accident->injured_holiday_town }} </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection