routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home_full', 'HomeController@index_full')->name('home_full');


Route::group(['namespace' => 'Admin',  'middleware' => ['auth', 'can:isAdmin'], 'prefix' => 'admin'], function (){

    /**
     *      Admin routes
     */
    Route::get('/accident/export', 'AccidentController@export')->name('accident_export');
    Route::get('/lessons/export', 'LessonsController@export')->name('lesson_export');

    Route::resource('user', 'UserController');
    Route::resource('accident', 'AccidentController');
    Route::resource('seasons', 'SeasonsController');
    Route::resource('lessons', 'LessonsController');
    Route::resource('niveau', 'NiveauController');
    Route::resource('accident-place', 'AccidentPlaceController');
    Route::resource('weather', 'WeatherController');
    Route::resource('snow-condition', 'SnowConditionController');
    Route::resource('accident-type', 'AccidentTypeController');
    Route::resource('piste-rescue', 'PisteRescueController');
    Route::resource('accident-gravity', 'AccidentGravityController');
    Route::resource('protection', 'ProtectionController');
    Route::resource('injury-type', 'InjuryTypeController');
    Route::resource('body-part', 'BodyPartController');
    Route::resource('discipline', 'DisciplineController');
    Route::resource('age-category', 'AgeCategoryController');
    Route::resource('accident-activity', 'AccidentActivityController');

});

Route::group(['namespace' => 'User',  'middleware' => ['auth', 'can:isSchool'], 'prefix' => 'user'], function (){

    /**
     *      User (=school) routes
     */

    Route::get('/lessons/{id}/export', 'LessonsController@export')->name('export_lesson');
    Route::get('/accident/{id}/export', 'AccidentController@export')->name('export_accident');

    Route::resource('lessons', 'LessonsController');
    Route::resource('accident', 'AccidentController');
    Route::get('/import', 'ImportLessonController@index')->name('import');
    Route::post('/import/upload', 'ImportLessonController@upload')->name('import_upload');
});

/**
 *      change locale
 */
Route::get('lang/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        session(['locale' => $locale]);
    }
    return redirect()->back();
})->name('language');

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'lessons';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['ski_kids', 'snowboard_kids', 'other_kids', 'ski_adults', 'snowboard_adults', 'other_adults', 'other_private', 'turnover_private', 'turnover_group', 'turnover_other', 'total_salary', 'season_id', 'user_id'];

    public function getTotalKidsLessonsAttribute(){
        return $this->ski_kids + $this->snowboard_kids + $this->other_kids;
    }

    public function getTotalAdultsLessonsAttribute(){
        return $this->ski_adults + $this->snowboard_adults + $this->other_adults;
    }

    public function getTotalTurnoverAttribute(){
        return $this->turnover_private + $this->turnover_group + $this->turnover_other;
    }

    public function season()
    {
        return $this->belongsTo('App\Season');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password', 'company', 'plz', 'town', 'language_id', 'region_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/Admin/LessonsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\AccidentPlace;
use App\Exports\LessonsExport;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Lesson;
use App\Season;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class LessonsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $lessons = Lesson::where('ski_kids', 'LIKE', "%$keyword%")
                ->orWhere('snowboard_kids', 'LIKE', "%$keyword%")
                ->orWhere('other_kids', 'LIKE', "%$keyword%")
                ->orWhere('ski_adults', 'LIKE', "%$keyword%")
                ->orWhere('snowboard_adults', 'LIKE', "%$keyword%")
                ->orWhere('other_adults', 'LIKE', "%$keyword%")
                ->orWhere('other_private', 'LIKE', "%$keyword%")
                ->orWhere('turnover_private', 'LIKE', "%$keyword%")
                ->orWhere('turnover_group', 'LIKE', "%$keyword%")
                ->orWhere('turnover_other', 'LIKE', "%$keyword%")
                ->orWhere('total_salary', 'LIKE', "%$keyword%")
                ->orWhere('season_id', 'LIKE', "%$keyword%")
                ->orWhere('user_id', 'LIKE', "%$keyword%")
                ->with('season')
                ->orderBy('user_id', 'asc')
                ->orderBy('season_id', 'desc')
                ->paginate($perPage);
        } else {
            $lessons = Lesson::with('season')
                ->orderBy('user_id', 'asc')
                ->orderBy('season_id', 'desc')
                ->paginate($perPage);
        }


        $seasons = Season::orderBy('id', 'desc')->pluck('title', 'id');

        return view('admin.lessons.index', compact('lessons'))->with('seasons', $seasons);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $seasons = Season::orderBy('id', 'desc')->pluck('title', 'id');
        $fks['users'] = User::orderBy('id', 'desc')->pluck('name','id');

        return view('admin.lessons.create')->with('seasons', $seasons)->with('fks', $fks);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'user_id' => 'required|unique_with:lessons,season_id',
            'season_id' => 'required'
        ], ['user_id.unique_with' => __('entities.error_season_duplicate')]);
        $requestData = $request->all();

        Lesson::create($requestData);

        return redirect('user/lessons')->with('flash_message', 'Lesson added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $lesson = Lesson::findOrFail($id);

        return view('admin.lessons.show', compact('lesson'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $lesson = Lesson::findOrFail($id);
        $seasons = Season::orderBy('id', 'desc')->pluck('title', 'id');

        $fks['users'] = User::orderBy('id', 'desc')->pluck('name','id');

        return view('admin.lessons.edit', compact('lesson'))->with('seasons', $seasons)->with('fks', $fks);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'user_id' => 'required'
        ]);
        $requestData = $request->all();

        $lesson = Lesson::findOrFail($id);
        $lesson->update($requestData);

        return redirect('admin/lessons')->with('flash_message', 'Lesson updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Lesson::destroy($id);

        return redirect('user/lessons')->with('flash_message', 'Lesson deleted!');
    }

    public function export(Request $request)
    {
        $season = Season::find($request->get('season_id'));

        $lessons = Lesson::where('season_id', $season->id);
        $file_name = Carbon::now()->toDateString() . '_Saison-' . str_slug($season->title) . '_lessons.xlsx';

        return (new LessonsExport())->forSeason($season->id)->download($file_name);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $user = User::where('name', 'LIKE', "%$keyword%")
                ->orWhere('password', 'LIKE', "%$keyword%")
                ->orWhere('company', 'LIKE', "%$keyword%")
                ->orWhere('plz', 'LIKE', "%$keyword%")
                ->orWhere('town', 'LIKE', "%$keyword%")
                ->orWhere('language_id', 'LIKE', "%$keyword%")
                ->orWhere('region_id', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $user = User::latest()->paginate($perPage);
        }

        return view('admin.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'name' => 'required',
            'id' => 'required|unique:users',
            'email' => 'required|unique:users',
            'password' => 'required'
		]);
        $requestData = $request->all();
        $requestData['password'] = bcrypt($requestData['password']);

        User::create($requestData);

        return redirect('admin/user')->with('flash_message', 'User added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users'
		]);
        $requestData = $request->all();

        if($requestData['password'] == null){
            unset($requestData['password']);
        }else{
            $requestData['password'] = bcrypt($requestData['password']);
        }

        $user = User::findOrFail($id);
        $user->update($requestData);

        return redirect('admin/user')->with('flash_message', 'User updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        User::destroy($id);

        return redirect('admin/user')->with('flash_message', 'User deleted!');
    }
}

app/Http/Controllers/User/ImportLessonController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Lesson;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImportLessonController extends Controller
{

    public static function importFtpFolder()
    {
        $directory = config('app.ftp_folder');
        $files = Storage::disk('local')->allFiles($directory);

        foreach ($files as $file){
                print("importing $file...\n");
                $result = self::import(storage_path('app/' . $file));
                if(count($result['errors']) === 0){
                    $filename = basename(storage_path('app/' . $file));
                    rename(storage_path('app/' . $file), storage_path() . '/app/' . $directory . '_archive/'. $filename);
                }else{
                    foreach ($result['errors'] as $error){
                        print($error);
                    }
                }
        }
    }

    public static function CsvKeys()
    {
        return [
            'user_id',
            'season_id',
            'ski_kids',
            'snowboard_kids',
            'other_kids',
            'ski_adults',
            'snowboard_adults',
            'other_adults',
            'other_private',
            'turnover_group',
            'turnover_private',
            'turnover_other',
            'total_salary',
        ];
    }

    public function index(Request $request)
    {
        return view('user.import_lessons.index');
    }

    public function upload(Request $request)
    {
        $this->validate($request, [
            'csv_file' => 'required'
        ]);

        $path = $request->file('csv_file')->getRealPath();
        $import_report = $this->import($path);

        return view('user.import_lessons.imported', $import_report);
    }

    public static function import($path)
    {
        $data = [];
        $errors = [];
        $successful = [];

        try{
            $data = array_map(function ($d) {
                return array_combine(self::CsvKeys(), array_values(str_getcsv($d, ";")));
            }, file($path));
        } catch (\ErrorException $exception){
            $errors[] = __('import.error_in_format');
        };

        foreach ($data as $i => $row) {
            $i++;
            try {
                Lesson::updateOrCreate(array_slice($row, 0, 2), $row);
                $successful[] = __('import.line_imported', ['line' => $i]);
            } catch (QueryException $exception) {
                $errors[] = __('import.error_in_line_not_imported', ['line' => $i, 'exception' => $exception->getMessage()]);
            }
        }

        return [
            'errors' => $errors,
            'successful' => $successful,
            'data' => $data
        ];
    }

}

resources/views/user/lessons/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.create_new_lesson') }}</div>
                    <div class="card-body">
                        <a href="{{ url('/user/lessons') }}" title="Back"><button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('entities.back') }}</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ url('/user/lessons') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('user.lessons.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/lessons/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.edit') }} {{ __('entities.lesson') }} {{ $lesson->season->title }}</div>
                    <div class="card-body">
                        <a href="{{ url('/user/lessons') }}" title="Back"><button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('entities.back') }}</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ url('/user/lessons/' . $lesson->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('user.lessons.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/lessons/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">{{ __('entities.lesson') }} {{ $lesson->season->title }} </div>
                    <div class="card-body">

                        <a href="{{ url('/user/lessons') }}" title="Back">
                            <button class="btn btn-outline-primary btn-sm"><i class="fa fa-arrow-left"
                                                                              aria-hidden="true"></i>
                                {{ __('entities.back') }}
                            </button>
                        </a>
                        <a href="{{ url('/user/lessons/' . $lesson->id . '/edit') }}" title="Edit Lesson">
                            <button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o"
                                                                      aria-hidden="true"></i> {{ __('entities.edit') }}
                            </button>
                        </a>

                        <form method="POST" action="{{ url('user/lessons' . '/' . $lesson->id) }}"
                              accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-outline-primary btn-sm" title="Delete Lesson"
                                    onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o"
                                                                                             aria-hidden="true"></i>
                                {{ __('entities.delete') }}
                            </button>
                        </form>
                        <br/>
                        <br/>
                        <h3 class="mt-4">{{ __('content.group_lessons') }}</h3>
                        <div class="row">
                            <div class="col">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <tbody>
                                        <tr>
                                            <th> {{ __('entities.ski_kids') }}</th>
                                            <td> {{ $lesson->ski_kids }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.snowboard_kids') }}</th>
                                            <td> {{ $lesson->snowboard_kids }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.other_kids') }}</th>
                                            <td> {{ $lesson->other_kids }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.total_lessons_kids') }}</th>
                                            <td> {{ $lesson->total_kids_lessons }} </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <tbody>
                                        <tr>
                                            <th> {{ __('entities.ski_adults') }}</th>
                                            <td> {{ $lesson->ski_adults }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.snowboard_adults') }}</th>
                                            <td> {{ $lesson->snowboard_adults }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.other_adults') }}</th>
                                            <td> {{ $lesson->other_adults }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.total_lessons_adults') }}</th>
                                            <td> {{ $lesson->total_adults_lessons }} </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <h3 class="mt-4">{{ __('content.private_lessons') }}</h3>
                        <div class="row">
                            <div class="col-6">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <tbody>
                                        <tr>
                                            <th> {{ __('entities.other_private') }}</th>
                                            <td> {{ $lesson->other_private }} </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <h3 class="mt-4">{{ __('content.turnover') }}</h3>
                        <div class="row">
                            <div class="col">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <tbody>
                                        <tr>
                                            <th> {{ __('entities.turnover_private') }}</th>
                                            <td> {{ $lesson->turnover_private }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.turnover_group') }}</th>
                                            <td> {{ $lesson->turnover_group }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('entities.turnover_other') }}</th>
                                            <td> {{ $lesson->turnover_other }} </td>
                                        </tr>
                                        <tr>
                                            <th> {{ __('content.total') }}</th>
                                            <td> {{ $lesson->total_turnover }} </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <h3 class="mt-4">{{ __('content.salary_sum') }}</h3>
                        <div class="row">
                            <div class="col-6">
                                <div class="table-responsive">
                                    <table class="table table-sm">
                                        <tbody>
                                        <tr>
                                            <th> {{ __('entities.total_salary') }}</th>
                                            <td> {{ $lesson->total_salary }} </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection